# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a20dde936504c380539467c0d08dce4d27ca6f0f73fef5cf6fd9b083ece7ab6d0e6ccfaa6174d346d21641acba1fadb3c857bf2d193aa0c539e31d58f5084854
  domain_name: http://localhost:3000
  cloudinary_name: staging-raheem
  cloudinary_key: 276232293483445
  cloudinary_secret: TeQQn5Yzx4ejUnVz3gYKOaRYY3k

test:
  secret_key_base: 0d02fc650e0824a9dbd6c32867bb4903a794b8b561033bcf54f9963dfc09cef010a623145a7f5889785bea36e31245a7b69133edfc9f9b6bd30e0bc5b6fbfe2d
  domain_name: http://localhost:3000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  cloudinary_name: <%= ENV["CLOUDINARY_NAME"] %>
  cloudinary_key: <%= ENV["CLOUDINARY_KEY"] %>
  cloudinary_secret: <%= ENV["CLOUDINARY_SECRET"] %>